MarsBar = print("Mars Bar Quantity 5 , 1$ each")
MarsBar =int(5)*int(1)
CansOfCoke =print("Cans of Coke Quantity 4 , 1.50$ each")
CansOfCoke =int(1.50)*int(4)
BagsOfCrisps =print("Bags Of Crisps Quantity 3 , 0.80$ each")
BagsOfCrisps =int(0.80)*int(3)
CupsOfTea =print("Cups Of Tea Quantity 2 , 2.00$ each")
CupsOfTea =int(2)*int(2)
SliceOfPan =print("Slice Of Pan Quantity 1 , 3.50$ each")
SliceOfPan =int(3.50)
print(MarsBar+CansOfCoke+CupsOfTea+BagsOfCrisps+SliceOfPan,"$")

number1 = int(input("Enter First Number: "))
number2= int(input("Enter Second Number: "))
sum = number1 + number2
print("The Answer is sum")
print(number1, "+",number2 , "=", sum)